---
all:
  vars:
    #ansible_user: vagrant
    ansible_password: vagrant
    # Ignora o pedido de aceitar a chave na primeira vez que conecta
    #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    # Aponta onde está a chave privada para autenticação
    #ansible_ssh_private_key_file: ".vagrant/machines/server-app/virtualbox/private_key"
    # Ignora o tipo de encriptação defasada na conexão
    #ansible_ssh_extra_args: "-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa"
    # Aponta o caminho do interpretador Python a ser utilizado
    #ansible_python_interpreter: "/usr/bin/python3"
linux:
  children:
    rocky:
      hosts:
        192.168.0.250:
    debian:
      hosts:
        192.168.0.251:
windows:
  hosts:
    192.168.0.252:
...