---
# tasks file for linux-update
- name: RedHat | Update System
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
    
- name: Debian | Update System
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

...