---
# tasks file for manage-files
- name: SYSTEM | Copy Files
  ansible.builtin.copy: src={{ item.src }}  dest={{ item.dest }}
  with_items:
    - { src: 'file1.conf', dest: '/tmp/file1.conf' }
    - { src: 'file2.conf', dest: '/tmp/file2.conf' }
    - { src: 'file3.conf', dest: '/tmp/file3.conf' }

- name: SYSTEM | Extract File
  ansible.builtin.unarchive:
    src: file.tar.gz
    dest: /tmp
...
