---

- name: Testing TAG
  hosts: all
  tasks:
    - name: SISOP | Set a hostname
      ansible.builtin.hostname:
        name: srv01
        use: systemd
      tags: hostname

    - name: SISOP | Disable SELINUX (Temp)
      ansible.builtin.selinux: state=disabled
      tags:
      - security
      - selinux

    - name: COPY | Copy ansible.cfg
      ansible.builtin.copy:
        src: ../ansible.cfg
        dest: /tmp/ansible.cfg
        owner: vagrant
        group: vagrant
        mode: 0644
      tags: copy

...