---
- name: Ansible Register
  hosts: all
  tasks:
    - name: SISOP | Find files
      ansible.builtin.find:
        path: /tmp
        patterns: '*.cfg'
      register: output

    - name: SISOP | Show files
      ansible.builtin.debug:
        msg: "{{ output }}"
...
