---

- name: Ansible Register Filters
  hosts: all
  tasks:
    - name: SISOP | Find files
      find:
        path: /tmp
        patterns: '*.cfg'
      register: output

    - name: SISOP | Show files
      debug:
        #msg: "{{ output.files | map(attribute='path') | first }}"
        #msg: "{{ output.files | map(attribute='path') | last }}"
        #msg: "{{ output.files | map(attribute='path') | list }}"
        msg: "{{ output.files | map(attribute='path') | sort }}"

...