---
- name: Ansible Conditionals Bool
  hosts: rocky9
  vars:
    backup: false
    snapshot: false
  tasks:
    - name: Run the task if 'backup' is true
      ansible.builtin.debug:
        msg: "Congratulations"
      when: backup | bool

    - name: Run the task if 'backup' is false
      ansible.builtin.debug:
        msg: "CRITICAL! Make backup."
      when: not backup
...
