---
- name: Ansible Stat
  hosts: rocky9
  tasks:
    - name: SISOP | Verificando se o arquivo existe
      ansible.builtin.stat:
        path: /tmp/ansible.cfg
      register: file

    - ansible.builtin.debug:
        msg: "File found"
      when: file.stat.exists

    - debug:
        msg: "File not found"
      when: file.stat.exists == false
...