---
- name: Ansible Loop Control
  hosts: rocky9
  tasks:
    - name: DNF | Install packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - net-tools
        - screen
      loop_control:
        pause: 3
...
