---
 - name: Ansible Handlers
   hosts: rocky9
   tasks:
    - name: NGINX | Change Listener
      ansible.builtin.replace:
       dest: /etc/nginx/nginx.conf
       regexp: 'listen 80 default_server;'
       replace: 'listen {{ ansible_default_ipv4.address }}:80 default_server;'
       notify: Restart Nginx
 
   handlers:
    - name: Restart Nginx
      ansible.builtin.service:
#      ansible.builtin.systemd:
       name: nginx
       state: restarted
       enabled: yes
...