---
- name: Ansible Prompt | Creating user on Linux
  hosts: all
  vars_prompt:
    - name: username
      prompt: Qual o seu nome de usuário?
      private: false
    - name: password
      prompt: Qual é a sua senha?
      private: true # Opcional, pois o padrão já é true
      encrypt: "md5_crypt" # Requer o passlib | pip3 install passlib
      confirm: yes
      salt_size: 7
    - name: shell
      prompt: Qual o seu shell?
      private: false
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: 'Usuário: {{ username }} | Senha: {{ password }} | Shell: {{ shell }}'
    - name: USER | Add user
      ansible.builtin.user:
        name: "{{ username }}"
        comment: "User create by Ansible"
        shell: "{{ shell }}"
        home: "/home/{{ username }}"
        password: "{{ password }}"
...